/*
 * +-------------------------------------------------------------------+
 * | (C) Copyright IBM Corp. 2025, 2026                                |
 * | SPDX-License-Identifier: Apache-2.0                               |
 * +-------------------------------------------------------------------+
 */
package topology

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/golang/glog"
	"github.com/ibm-aiu/spyre-device-plugin/pkg/utils"
	spyrev1alpha1 "github.com/ibm-aiu/spyre-operator/api/v1alpha1"
	spyreconst "github.com/ibm-aiu/spyre-operator/const"
	"github.com/ibm-aiu/spyre-operator/pkg/types/pcitopov2"
	pluginapi "k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1"
)

var (
	// DefaultTopologyFolder defines a default folder contains all nodes' topology files
	// This path is mount path from custom config map.
	DefaultTopologyFolder = "/etc/aiu/topology"
	// MetadataTopologyFilepath defines a path of topology file generated by init container
	MetadataTopologyFilepath = "/usr/local/etc/device-plugins/metadata/topo.json"

	// DynamicTopologyFilepath defines the temporary file for filtered/processed topology
	DynamicTopologyFilepath = "/tmp/spyre-device-plugin/topo.json"

	PciTopology    *pcitopov2.Pcitopo
	PciTopoCommand = "pcitopo"

	// IgnoreMetadataKey set this env to `true` to skip metadata file
	IgnoreMetadataKey = "IGNORE_EXTERNAL_METADATA"
)

// GetPciTopology returns Pcitopo from topology file (topo.json),
// filtered out the missing devices if filterMissing flag set.
// If the global PciToplogy is set, return the set topology.
// If not, check if topologyFilepath is given and valid.
// If given topologyFilepath is valid, unmarshal to Pcitopo.
// If not, return pseudo topology if pseudo mode is enabled.
// Otherwise, try generating topology from pcitopo tool and write a static file.
func GetPciTopology(topologyFilepath string, filterMissing bool) (pcitopov2.Pcitopo, error) {
	pseudoMode := os.Getenv(spyrev1alpha1.PseudoDeviceMode.EnvKey()) == spyreconst.ModeEnabledValue
	if PciTopology != nil {
		return *PciTopology, nil
	}

	// replace empty filepath with default path
	if topologyFilepath == "" {
		// Use current topology file which checks dynamic location first
		topologyFilepath = GetCurrentTopologyFile()
		if topologyFilepath == "" {
			return pcitopov2.Pcitopo{}, fmt.Errorf("failed to get topology file")
		}
	}
	var err error
	var s []byte
	if s, err = os.ReadFile(topologyFilepath); err != nil {
		return pcitopov2.Pcitopo{}, err
	}
	glog.Infof("use topology data from %s", topologyFilepath)
	pcitopo, err := pcitopov2.UnmarshalPciTopo(s)
	if err == nil {
		PciTopology = &pcitopo
	}

	// If filterMissing is requested and not in pseudo mode, filter out physically missing devices
	if filterMissing && !pseudoMode && pcitopo.Devices != nil {
		filteredTopo := filterOutMissingDeviceFromTopology(pcitopo)
		return filteredTopo, nil
	}
	return pcitopo, err
}

// filterOutMissingDeviceFromTopology removes missing device from pciTopo.
// The device is considered missing if it does not present in the device path.
// The missing devices are removed from the device list as well as the peer list
// The number of device must be updated.
func filterOutMissingDeviceFromTopology(pciTopo pcitopov2.Pcitopo) pcitopov2.Pcitopo {
	presentMap := make(map[string]bool, len(pciTopo.Devices)+len(pciTopo.SpyreVfDevices))
	for pciAddress := range pciTopo.Devices {
		present := utils.PfExist(pciAddress)
		presentMap[pciAddress] = present
		if !present {
			delete(pciTopo.Devices, pciAddress)
		}
	}

	for pciAddress := range pciTopo.SpyreVfDevices {
		present := utils.PfExist(pciAddress)
		presentMap[pciAddress] = present
		if !present {
			delete(pciTopo.SpyreVfDevices, pciAddress)
		}
	}
	for _, device := range pciTopo.Devices {
		if device.Peers.Peer0 != nil {
			for peer := range device.Peers.Peer0 {
				if peerPresent := presentMap[peer]; !peerPresent {
					delete(device.Peers.Peer0, peer)
				}
			}
		}
		if device.Peers.Peer1 != nil {
			for peer := range device.Peers.Peer1 {
				if peerPresent := presentMap[peer]; !peerPresent {
					delete(device.Peers.Peer1, peer)
				}
			}
		}
		if device.Peers.Peer2 != nil {
			for peer := range device.Peers.Peer2 {
				if peerPresent := presentMap[peer]; !peerPresent {
					delete(device.Peers.Peer2, peer)
				}
			}
		}
	}
	for _, device := range pciTopo.SpyreVfDevices {
		if device.SpyreVfPeers.Peer0 != nil {
			for peer := range device.SpyreVfPeers.Peer0 {
				if peerPresent := presentMap[peer]; !peerPresent {
					delete(device.SpyreVfPeers.Peer0, peer)
				}
			}
		}
		if device.SpyreVfPeers.Peer1 != nil {
			for peer := range device.SpyreVfPeers.Peer1 {
				if peerPresent := presentMap[peer]; !peerPresent {
					delete(device.SpyreVfPeers.Peer1, peer)
				}
			}
		}
		if device.SpyreVfPeers.Peer2 != nil {
			for peer := range device.SpyreVfPeers.Peer2 {
				if peerPresent := presentMap[peer]; !peerPresent {
					delete(device.SpyreVfPeers.Peer2, peer)
				}
			}
		}
	}

	pciTopo.NumDevices = len(pciTopo.Devices)
	pciTopo.SpyreVfNumDevices = len(pciTopo.SpyreVfDevices)
	return pciTopo
}

// FilterTopologyByDeviceHealth filters topology to only include healthy devices from the original topology.
// This creates a filtered copy that includes all healthy devices from the original source of truth.
// If a device is healthy but not in the current topology, it gets restored from the original.
// Unhealthy devices are removed and peer lists are cleaned up to maintain consistency.
func FilterTopologyByDeviceHealth(originalTopo pcitopov2.Pcitopo, healthyDevices map[string]bool) pcitopov2.Pcitopo {
	filteredTopo := originalTopo
	filteredDevices := make(map[string]pcitopov2.Device)
	filteredVfDevices := make(map[string]pcitopov2.Device)

	// Restore healthy devices from original topology
	if originalTopo.Devices != nil {
		for pciAddress, device := range originalTopo.Devices {
			if healthyDevices[pciAddress] {
				filteredDevices[pciAddress] = device
			}
		}
	}
	if originalTopo.SpyreVfDevices != nil {
		for pciAddress, device := range originalTopo.SpyreVfDevices {
			if healthyDevices[pciAddress] {
				filteredVfDevices[pciAddress] = device
			}
		}
	}

	filteredTopo.Devices = filteredDevices
	filteredTopo.SpyreVfDevices = filteredVfDevices

	// Clean up peer references for regular devices - only keep healthy peers
	for _, device := range filteredTopo.Devices {
		if device.Peers.Peer0 != nil {
			for peer := range device.Peers.Peer0 {
				if !healthyDevices[peer] {
					delete(device.Peers.Peer0, peer)
				}
			}
		}
		if device.Peers.Peer1 != nil {
			for peer := range device.Peers.Peer1 {
				if !healthyDevices[peer] {
					delete(device.Peers.Peer1, peer)
				}
			}
		}
		if device.Peers.Peer2 != nil {
			for peer := range device.Peers.Peer2 {
				if !healthyDevices[peer] {
					delete(device.Peers.Peer2, peer)
				}
			}
		}
	}

	for _, device := range filteredTopo.SpyreVfDevices {
		if device.SpyreVfPeers.Peer0 != nil {
			for peer := range device.SpyreVfPeers.Peer0 {
				if !healthyDevices[peer] {
					delete(device.SpyreVfPeers.Peer0, peer)
				}
			}
		}
		if device.SpyreVfPeers.Peer1 != nil {
			for peer := range device.SpyreVfPeers.Peer1 {
				if !healthyDevices[peer] {
					delete(device.SpyreVfPeers.Peer1, peer)
				}
			}
		}
		if device.SpyreVfPeers.Peer2 != nil {
			for peer := range device.SpyreVfPeers.Peer2 {
				if !healthyDevices[peer] {
					delete(device.SpyreVfPeers.Peer2, peer)
				}
			}
		}
	}

	filteredTopo.NumDevices = len(filteredTopo.Devices)
	filteredTopo.SpyreVfNumDevices = len(filteredTopo.SpyreVfDevices)
	return filteredTopo
}

// EnsureDynamicTopologyFiltered ensures there's a dynamic filtered topology file.
// If the dynamic file already exists, this is a no-op. Otherwise, it reads the
// original topology, filters missing devices, and writes the dynamic file.
func EnsureDynamicTopologyFiltered() error {
	// If dynamic already exists, nothing to do
	if utils.PathExists(DynamicTopologyFilepath) {
		return nil
	}

	// Prefer original immutable file as source of truth
	original := GetOriginalTopologyFile()
	if original == "" {
		return fmt.Errorf("no original topology file available to generate dynamic topology")
	}

	topo, err := GetPciTopology(original, true)
	if err != nil {
		return fmt.Errorf(
			"dynamic topology generation failed: unable to parse and filter original topology file %q: %w",
			original, err)
	}

	if err := SaveDynamicTopology(topo); err != nil {
		return fmt.Errorf(
			"dynamic topology generation failed: unable to save filtered topology to %q: %w",
			DynamicTopologyFilepath,
			err,
		)
	}
	return nil
}

func GetTopologyFile() string {
	// first check metadata topology filepath
	if os.Getenv(IgnoreMetadataKey) != "true" && utils.PathExists(MetadataTopologyFilepath) {
		return MetadataTopologyFilepath
	}
	nodeName := utils.GetNodeName()
	topologyFilepath := filepath.Join(DefaultTopologyFolder, nodeName)
	if !utils.PathExists(topologyFilepath) {
		glog.Info("Topology file does not exist")
		return ""
	}
	return topologyFilepath
}

// GetOriginalTopologyFile returns the path to the original immutable topology file.
// This should not be modified.
func GetOriginalTopologyFile() string {
	if os.Getenv(IgnoreMetadataKey) != "true" && utils.PathExists(MetadataTopologyFilepath) {
		return MetadataTopologyFilepath
	}
	nodeName := utils.GetNodeName()
	originalTopologyFilepath := filepath.Join(DefaultTopologyFolder, nodeName)
	if !utils.PathExists(originalTopologyFilepath) {
		glog.Info("Original topology file does not exist")
		return ""
	}
	return originalTopologyFilepath
}

// GetCurrentTopologyFile returns the path to the current working topology file.
// This checks for dynamic topology first, then falls back to original sources.
func GetCurrentTopologyFile() string {
	if utils.PathExists(DynamicTopologyFilepath) {
		return DynamicTopologyFilepath
	}
	return GetTopologyFile()
}

// SaveDynamicTopology saves a filtered/processed topology to the dynamic location.
// This allows preserving original topology while maintaining a current working version.
func SaveDynamicTopology(topo pcitopov2.Pcitopo) error {
	dynamicFolder := filepath.Dir(DynamicTopologyFilepath)
	if err := utils.CreateFolderIfNotExists(dynamicFolder); err != nil {
		return fmt.Errorf("failed to create dynamic topology folder: %w", err)
	}
	data := []byte(topo.String())

	if err := os.WriteFile(DynamicTopologyFilepath, data, 0644); err != nil {
		return fmt.Errorf("failed to write dynamic topology file: %w", err)
	}

	glog.V(1).Infof("Saved dynamic topology to %s", DynamicTopologyFilepath)
	return nil
}

// GetMaxValidPeers returns a single group of requested tier + self-allocated devices
// Topology-aware resource for VFs is not supported without external reservation mode.
// This function should not be activated on vf resource.
func GetMaxValidPeers(
	deviceMap map[string]*pluginapi.Device,
	resourceName string,
	selfAllocation map[string]bool,
) map[string]*pluginapi.Device {
	topo, err := GetPciTopology("", false)
	if err != nil {
		glog.Warningf("try GetMaxValidPeers but topol is nil, return as-is")
		return deviceMap
	}
	if strings.Contains(resourceName, "vf") {
		glog.Warningf("GetMaxValidPeers on vf resource, return as-is")
		return deviceMap
	}
	maxValidGroup := make(map[string]*pluginapi.Device)
	for dev := range deviceMap {
		if allocated, found := selfAllocation[dev]; found && allocated {
			// self allocated, not available
			continue
		}
		if info, found := topo.Devices[dev]; found {
			peerMap := make(map[string]int)
			for peer, hop := range info.Peers.Peer0 {
				peerMap[peer] = hop
			}
			switch {
			case strings.HasSuffix(resourceName, spyreconst.TierOneResourceNameSuffix):
				for peer, hop := range info.Peers.Peer1 {
					peerMap[peer] = hop
				}
			case strings.HasSuffix(resourceName, spyreconst.TierTwoResourceNameSuffix):
				for peer, hop := range info.Peers.Peer1 {
					peerMap[peer] = hop
				}
				for peer, hop := range info.Peers.Peer2 {
					peerMap[peer] = hop
				}
			}
			if len(peerMap) == 0 {
				// has not peer info
				continue
			}
			validPeers := make(map[string]*pluginapi.Device)
			validPeers[dev] = deviceMap[dev]
			for peer := range peerMap {
				if allocated, found := selfAllocation[peer]; found && allocated {
					// self allocated, not available
					continue
				}
				if existingPeer, exists := deviceMap[peer]; exists {
					validPeers[peer] = existingPeer
				}
			}
			if len(validPeers) > len(maxValidGroup) {
				maxValidGroup = validPeers
				glog.Infof("set new valid group of %s: %v", resourceName, maxValidGroup)
			}
		}
	}

	glog.Infof("max valid group of %s: %v", resourceName, maxValidGroup)
	// append with self-allocated list
	for dev, allocated := range selfAllocation {
		if allocated {
			if info, exists := deviceMap[dev]; exists {
				glog.Infof("append self allocated list in %s: %s", resourceName, dev)
				maxValidGroup[dev] = info
			}
		}
	}

	return maxValidGroup
}
