# +-------------------------------------------------------------------+
# | Copyright (c) 2025, 2026 IBM Corp.                                |
# | SPDX-License-Identifier: Apache-2.0                               |
# +-------------------------------------------------------------------+

name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write # Crucial for pushing to ghcr.io

jobs:
  build:
    uses: modassarrana89-new/spyre-operator-actions/.github/workflows/build-image.yaml@multi-arch-build
    with:
      dockerfile: ./images/Dockerfile.ubi9
