# +-------------------------------------------------------------------+
# | (C) Copyright IBM Corp. 2025, 2026                                 |
# | SPDX-License-Identifier: Apache-2.0.                              |
# +-------------------------------------------------------------------+

name: Ensure Pre-commit

on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  pre-commit:
    uses: ibm-aiu/spyre-operator-actions/.github/workflows/pre-commit.yaml@main
    secrets:
      gh-token: ${{ secrets.GH_PAT }}
